#!/usr/bin/python
import subprocess,threading,sys,os,signal

if len(sys.argv) < 3:
    print "Usage: perform seconds command [args...]"
    sys.exit(1)


# preexec_fn=os.setsid and os.killpg work together to do the magic
p = subprocess.Popen(["/bin/sh","-c",sys.argv[2]], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, preexec_fn=os.setsid)
#p = subprocess.Popen(sys.argv[2:], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, preexec_fn=os.setsid)
t = threading.Timer(int(sys.argv[1]), os.killpg, (p.pid, signal.SIGKILL))

try:
    t.start()
    stdout=p.communicate()[0]
finally:   
    expired=not t.isAlive()
    t.cancel()
p.stdout.close()
status=p.returncode
print "expired=%d status=%d stdout=\n%s"%(expired, status,stdout)
